package app.aspen.data.consent

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Android [ConsentCipher]: AES-256/GCM with a key minted in and never leaving the AndroidKeyStore
 * (hardware-backed where available). The key is created on first use under [KEY_ALIAS] and reused.
 *
 * Not yet hardware-verified on a device/emulator from this environment — that verification is a
 * tracked Phase-2 leftout (docs/STATUS.md). The IV is generated by the cipher per-encrypt and is
 * length-prefixed onto the ciphertext.
 */
private class KeystoreConsentCipher : ConsentCipher {

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build(),
        )
        return generator.generateKey()
    }

    override fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv
        val body = cipher.doFinal(plaintext)
        return byteArrayOf(iv.size.toByte()) + iv + body
    }

    override fun decrypt(ciphertext: ByteArray): ByteArray {
        val ivLen = ciphertext[0].toInt()
        val iv = ciphertext.copyOfRange(1, 1 + ivLen)
        val body = ciphertext.copyOfRange(1 + ivLen, ciphertext.size)
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
        return cipher.doFinal(body)
    }

    private companion object {
        const val TRANSFORM = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
    }
}

private const val ANDROID_KEYSTORE = "AndroidKeyStore"
private const val KEY_ALIAS = "aspen.consent.v1"

actual fun platformConsentCipher(): ConsentCipher = KeystoreConsentCipher()
